# db_joint data
train_align: data/alignment/train
train_pitch: data/pitch_beat_extraction/train
train_wav: data/wav_info/train
val_align: data/alignment/dev
val_pitch: data/pitch_beat_extraction/dev
val_wav: data/wav_info/dev

# augment related
random_crop: True
crop_min_length: 100

Hz2semitone: True
semitone_size: 59
semitone_min: F_1
semitone_max: D_6

phone_shift_size: 2
semitone_shift: False

# model related
model_type: LSTM
normalize: True
# double_mel_loss: False
perceptual_loss: 1e-4

accumulation_steps: 1
auto_select_gpu: False
# gpu_id: 1

max_epochs: 100

batchsize: 10    # 10
num_workers: 8

mask_free: False
use_asr_post: False
sampling_rate: 22050
nfft: 2048
feat_dim: 1025
n_mels: 80

frame_length: 0.06
frame_shift: 0.03

hidden_size: 256
embedding_size: 256
num_rnn_layers: 3
num_frames: 500
char_max_len: 100
optimizer: adam
lr: 0.001
phone_size: 68
singer_size: 10
seed: 777

train_step_log: 180
dev_step_log: 6

